name: taluxi_common
description: Common widgets for taluxi project.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
#  assets_audio_player: ^3.1.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  real_time_location:
    path: ../real_time_location
#    git:
#      url: https://github.com/NonymousMorlock/taluxi_real_time_location.git
#      ref: main
  user_manager:
    git:
      url: https://github.com/NonymousMorlock/taluxi_user_manager.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/images/
    - assets/images/trophies/
    - assets/images/animations/
